//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temporizador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Temporizador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream alarma {
            get {
                return ResourceManager.GetStream("alarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niue;11;True
        ///Samoa Americana;11;True
        ///Islas Cook;10;True
        ///Estados Unidos;10;True
        ///Polinesia Francesa;10;True
        ///Canadá;9;True
        ///Polinesia Francesa;9;True
        ///Estados Unidos;9;True
        ///Canadá;8;True
        ///Canadá;8;True
        ///Islas Pitcairn;8;True
        ///Canadá;7;True
        ///Canadá;7;True
        ///Belice;6;True
        ///Canadá;6;True
        ///Chile;6;True
        ///Ecuador;6;True
        ///Bahamas;5;True
        ///Canadá;5;True
        ///Brasil;5;True
        ///Colombia;5;True
        ///Cuba;5;True
        ///Chile;5;True
        ///Ecuador;5;True
        ///Perú;5;True
        ///Anguila;4;True
        ///Bahamas;4;True
        ///Brasil;4;True
        ///Bolivia;4;True
        ///Chile;4;Tru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Fila {
            get {
                return ResourceManager.GetString("Fila", resourceCulture);
            }
        }
    }
}
